server:
  port: 8985
rancher:
  accessKey: 607D20C33A9B0AEDB503
  secretKey: XNCZdDzpJNysfmZMVhwY9PXoRGCCffUkfA9nuarv
  host: http://114.116.99.165
#  accessKey: 7DCF4AB1D5B5AA007CDC
#  secretKey: hpvUwvwgT1E6eaEAPBJYVhXw814JF24XUbfa7omF
#  host: http://192.168.20.112
  port: 8080
  projectId: 1a5
  deleteTimeDefault: 60
spring:
  redis:
    host: 114.116.99.165
    port: 6379
    password: luutqf

  rabbitmq:
    addresses: 114.116.99.165
    port: 5672
    username: luutqf
    password: 00000aaaaa
